# MORDOR_PORT
# ISENGARD_PORT
version: '3'

services:
  isengard:
    image: golang:latest
    container_name: isengard
    environment:
      - GO_ENV=production
      - ISENGARD_PORT=8000
    volumes:
      - ./isengard
    command: go run ./server/server.go
    working_dir: ./
    ports:
      - "8000:8000"

  mordor:
    image: node:latest
    container_name: node-container-1
    environment:
      - NODE_ENV=production
      - MORDOR_PORT=4000
    volumes:
      - ./mordor
    command: bun start
    working_dir: ./
    ports:
      - "4000:4000"

  gateway:
    image: node:latest
    container_name: node-container-1
    environment:
      - NODE_ENV=production
      - MORDOR_PORT=4000
      - ISENGARD_PORT=8000
    volumes:
      - ./gateway
    command: bun start
    working_dir: ./
    ports:
      - "6473:6473"

  testing-api-node:
    image: node:latest
    container_name: testing-api
    environment:
      - NODE_ENV=production
      - NODE_PORT=6473
    volumes:
      - ./test
    command: npm start
    working_dir: ./
    ports:
      - "3001:3001"
