version: "3"

includes:
  lame-api:
    taskfile: ./lameAPI
    dir: ./lameAPI

  snack-bro:
    taskfile: ./snackBro
    dir: ./snackBro

tasks:
  default:
    cmds:
      - task -l
    silent: true
