version: '3'

tasks:
  default:
    cmds:
      - task -l
    silent: true
  run:
    desc: runs the presentation
    cmds:
      - bun dev
    
  pdf:
    desc: runs the presentation
    cmds:
      - bun export
    
  setup:
    desc: setups deps
    cmds:
      - bun install
    

