version: '3'

tasks:
  default:
    cmds:
      - task -l
  setup:
    desc: installs deps
    cmds: 
      - npm i
  start:
    desc: starts the server
    cmds:
      - npm run start
  stage:
    desc: builds and executes built files
    cmds:
      - npm run start:prod