version: '3'

tasks:
  default:
    cmds:
      - task -l
    silent: true
  run:  
    desc: runs the application
    cmds:
      - cargo run
    silent: true
  build:
    desc: builds the application
    cmds:
      - cargo build
      - cp target/debug/lameAPI ./lameAPI
    silent: true
