version: '3'

includes:
  gographql:
    dir: ./server
    taskfile: ./server

tasks:
  default:
    cmds:
      - task -l
    silent: true

  setup:
    desc: install deps
    cmds:
      - go mod tidy
  run:
    desc: runs server
    cmds:
      - go run server.go
