# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task -l
    silent: true

  run:
    cmds:
      - bun run dev
    silent: true

  setup:
    cmds:
      - bun install
    silent: true
