FROM golang:1.21 AS builder
RUN apt update -y &&  apt -y upgrade && apt -y install curl

WORKDIR /app

RUN sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d

COPY . .

RUN go mod tidy

RUN task build

FROM alpine:latest

WORKDIR /app

# Copy only the necessary files from the previous stage
COPY --from=builder /app/server .

# Expose the port your application listens on
EXPOSE 8080

# Command to run your application
CMD ["./myapp"]
