version: '3'

includes:
  gographql:
    dir: ./server
    taskfile: ./server
  bff:
    dir: ./bff
    taskfile: ./bff

tasks:
  default:
    cmds:
      - task -l
    silent: true

  run:
    desc: runs playground and server at the same time
    cmds:
      - task -p bff:start  gographql:start
